### ISSUE TITLE
Problem checking out version 4.0.0

### ISSUE THREAD

**Issue by dhando** [OpenMDAO/pyCycle#42]
Versions 3.5.0 and 4.0.0 are not tagged and can't be checked out. When version 3.4.0 is checked out while following installation instructions, version 3.0.0 is installed instead.

**Comment by dhando** [comment]
I dug into this a little more... if the development version is checked out then it will install version 3.9.9 according to the conda package listing. The code that is implemented seems to include all of the latest changes and does include the thermo model features of version 4, so it appears to me that this might only be a hiccup in the conda package list version number that shows up. I haven't checked to see if other versions check out properly, but I also can't check out version 3.5.0 since it is not tagged.

**Comment by younes-jc** [comment]
I have the same issue: when using "git tag", only versions 1.0 / 3.0.0 / 3.2.0 / 3.4.0 appear. I have checked out to 3.4.0, then installed pyCycle but I don't see the changes included in version 4.0. Which is the development version that you checked out in order to have the new updates of version 4? I have version 3.8.0 of openmdao.

**Comment by JustinSGray** [comment]
The latest versions have been tagged. I don't recommend you use anything other than tagged releases unless you're really brave. I make no promises about the correctness of the main branch outside of releases :)
